### ISSUE TITLE
Path params need to be required

### ISSUE THREAD

**Issue by an0ther-koni** [k0kubun/rspec-openapi#1]
Hi!

Swagger Editor complains about an error, that the generated path params need to be required.

Adding `required: true` in the generation, should fix it.

**Comment by k0kubun** [comment]
Thank you for reporting it. I fixed it in https://github.com/k0kubun/rspec-openapi/commit/592e1aeb4181decdf0bb714564038575eb8a4951 and released it as v0.1.2.

I'll try looking at Swagger Editor by myself later too.
