### ISSUE TITLE
Is it supported on Hanami?

### ISSUE THREAD

**Issue by jorbs** [k0kubun/rspec-openapi#15]
I have a Hanami project (https://hanamirb.org/) and tried to use this gem, but the following error happens:

```
Failures:

  1) Companies #index returns a list of companies
     Failure/Error: get '/api/companies'
     
     NoMethodError:
       undefined method `get' for #<RSpec::ExampleGroups::Companies::Index:0x00007f8cc8b53a18>
       Did you mean?  gets
                      gem
     # ./spec/api/controllers/companies_controller_spec.rb:4:in `block (3 levels) in <top (required)>'
```

**Comment by k0kubun** [comment]
As your file name implies, it's not *request specs*, right? It's not for controller specs, which seem to be used according to your file name.

> rspec-openapi can generate OpenAPI specs from request specs
> https://github.com/k0kubun/rspec-openapi/blob/master/README.md

**Comment by jorbs** [comment]
But does the filename matter in this case? Here is my updated spec source code:

```
# ./spec/requests/companies_spec.rb
RSpec.describe 'Companies', type: :request do
  describe '#index' do
    it "returns a list of companies" do
      get '/api/companies'
      expect(response.status).to be(200)
    end
  end
end
```

**Comment by k0kubun** [comment]
ok, could you please prepare a repository that reproduces your issue? Then I can take a look at fixing the error for you.

**Comment by k0kubun** [comment]
Also, I'd like to double check, does your request spec work when you uninstall rspec-openapi?

**Comment by jorbs** [comment]
Okay. I fixed the error above by using the gem [rspec-hanami](https://github.com/davydovanton/rspec-hanami). Basically, itincludes the request helpers.

> Also, I'd like to double check, does your request spec work when you uninstall rspec-openapi?

Yes. If I ran `rspec spec/requests/companies_spec.rb` is passes. Now `OPENAPI=1 rspec spec/requests/companies_spec.rb` throws:

```
F

Failures:

  1) Companies #index returns a list of companies
     Failure/Error:
       def request(request)
         @response = ::Hanami.app.call(request.env)
       end
     
     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # ~/proj/gems/rspec-hanami-0.4.0/lib/rspec/hanami/request_helpers.rb:49:in `request'
     # ~/proj/gems/rspec-openapi-0.3.9/lib/rspec/openapi/record_builder.rb:13:in `build'
     # ~/proj/gems/rspec-openapi-0.3.9/lib/rspec/openapi/hooks.rb:12:in `block in <top (required)>'

Finished in 0.01846 seconds (files took 1.9 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/requests/companies_spec.rb:3 # Companies #index returns a list of companies
```

**Comment by k0kubun** [comment]
Thanks for confirming that. Then, please:

> prepare a repository that reproduces your issue

**Comment by jorbs** [comment]
Hi @k0kubun,

I've followed the guide https://guides.hanamirb.org/actions/testing/#requests-tests to test my API requests and the error above doesn't happen anymore. Although, if I ran `OPENAPI=1 rspec spec/requests/companies_spec.rb`, no YAML file is generated.

As requested, I created an example repo that you can use https://github.com/jorbs/hanami-bookself.

**Comment by k0kubun** [comment]
Thanks!

Looking at your code, it seems there's technically no "request spec" in your repository, because:

> https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec
> Request specs are marked by :type => :request or if you have set config.infer_spec_type_from_file_location! by placing them in spec/requests

The explanation is coming from rspec-rails and therefore you can't use `config.infer_spec_type_from_file_location!` with rspec-hanami. What you can do instead is to specify `:type => :request` metadata in your spec, like:

```diff
diff --git a/spec/api/requests/books_spec.rb b/spec/api/requests/books_spec.rb
index 7aff21e..fce363e 100644
--- a/spec/api/requests/books_spec.rb
+++ b/spec/api/requests/books_spec.rb
@@ -1,4 +1,4 @@
-RSpec.describe "books" do
+RSpec.describe "books", type: :request do
   include Rack::Test::Methods

   # app is required by Rack::Test
@@ -11,4 +11,4 @@ RSpec.describe "books" do
       expect(last_response.status).to be(200)
     end
   end
 end
```

and I could confirm a document is generated for the request spec, although the response seems to be empty and the document is not giving any useful information when you do not populate your database.

The tagging is necessary because otherwise rspec-openapi wouldn't be able to tell which specs should be ignored when you run all specs with `OPENAPI=1 rspec`.
