### ISSUE TITLE
How to use the experimental description_builder

### ISSUE THREAD

**Issue by ekampp** [k0kubun/rspec-openapi#21]
Hi there. 

I'm back at trying this out, and I want to improve the explanation given in the documentation so it has more context than just explaining the request/response pattern. 

I see that there is a `description_builder` feature. But I don't see any examples or guidance on how to use it. Where should I look?

**Comment by k0kubun** [comment]
Wasn't https://github.com/k0kubun/rspec-openapi#configuration enough? I document every config in README.md.

**Comment by ekampp** [comment]
@k0kubun, it was after digging into the source code. It wasn't quite enough at first glance. But I found it and closed the issue 👍🏼
