### ISSUE TITLE
Allow the type of RSpec test to be configurable (not just :request)

### ISSUE THREAD

**Issue by justinschier** [k0kubun/rspec-openapi#33]
## Current Behaviour
All OpenAPI requests get run on the `type: :request`.

## Desired Behaviour
We would like to be able to run on one or more arbitrary types, e.g. `type: :flow`. This would mean changing file 
[hooks.rb](https://github.com/k0kubun/rspec-openapi/blob/master/lib/rspec/openapi/hooks.rb) to be configurable.

This will allow us to generate our schema.yaml from our flow specs as well as from our request specs.

**Comment by justinschier** [comment]
I just submitted a PR to address this.

**Comment by k0kubun** [comment]
forgot closing this when I merged #32. Thank you!
