### ISSUE TITLE
Can we override schema version to 3.0.0 ?

### ISSUE THREAD

**Issue by raghuvarmabh** [k0kubun/rspec-openapi#34]
Hi,
First of all thanks for this wonderful gem. It makes life easy without learning another DSL for documentation. 
Can we change the default version to 3.0.0 ? I see it is 3.0.3 in the source code.

**Comment by k0kubun** [comment]
Yeah sure. As you're already familiar with where it's used, could you file a pull request to add the config in https://github.com/k0kubun/rspec-openapi/blob/master/lib/rspec/openapi.rb and use it, also documenting it in README.md?
