### ISSUE TITLE
is the library rails specific?

### ISSUE THREAD

**Issue by AlexeyMatskevich** [k0kubun/rspec-openapi#5]
I try to setup simple application written on [Roda](https://roda.jeremyevans.net/). For request test I use rspec + [rack-test](https://github.com/rack/rack-test)
My simple spec
```ruby
describe "School", type: :request do
  ...
  it "return 200" do
    post "/school", {id: 1}.to_json, "CONTENT_TYPE" => "application/json"
    expect(last_response.status).to eq(200)
  end
end
```
When I run the tests, they pass successfully but nothing is generated and does not happen.

**Comment by AlexeyMatskevich** [comment]
After `require "rspec/openapi"` in spec get errors:
```bash
     Failure/Error:
       def request(uri, env = {}, &block)
         uri = parse_uri(uri, env)
         env = env_for(uri, env)
         process_request(uri, env, &block)
       end
     
     ArgumentError:
       wrong number of arguments (given 0, expected 1..2)
     Shared Example Group: "user success login" called from ./spec/idp_spec.rb:20
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:116:in `request'
     # /usr/local/bundle/gems/rspec-openapi-0.2.2/lib/rspec/openapi/hooks.rb:11:in `block in <top (required)>'
```

**Comment by k0kubun** [comment]
It's currently so https://github.com/k0kubun/rspec-openapi#current-limitations, but I can take a look at supporting Roda + rack-test.

**Comment by k0kubun** [comment]
I added an initial support of rack-test and non-Rails apps like Roda. Please try v0.3.0.

Though `path` and `summary` [here](https://github.com/k0kubun/rspec-openapi/blob/36cbbe0f02273539a948cb4309a6931d20e6b351/lib/rspec/openapi/record_builder.rb#L23-L24) are probably not that great compared to ones generated for Rails. I'd appreciate your input or patch for these two lines as a Roda user.

**Comment by AlexeyMatskevich** [comment]
It worked
