### ISSUE TITLE
RSpec::OpenAPI.server_urls -> RSpec::OpenAPI.servers (hash)

### ISSUE THREAD

**Issue by tashua314** [k0kubun/rspec-openapi#60]
I want to be able to set description in addition to url in the information of OpenAPI Server.

https://github.com/k0kubun/rspec-openapi/blob/cb634d0b534339d60d2e18c1bfc9b31ef9be6bb8/lib/rspec/openapi/default_schema.rb#L9

## refs
Openapi documentation
https://oai.github.io/Documentation/specification-servers.html

**Comment by k0kubun** [comment]
@AS-AlStar Any comments? If you're okay with that change, I'm okay with accepting this change too. But I don't want to maintain `server_urls` and `servers` at the same time, so I'd expect the change to remove https://github.com/k0kubun/rspec-openapi/pull/30 written by you.

**Comment by AS-AlStar** [comment]
Ok, I'm accept with that changes.

**Comment by k0kubun** [comment]
Thank you!

@tashua314 Could you check if this is what you want? https://github.com/k0kubun/rspec-openapi/pull/61

**Comment by tashua314** [comment]
@k0kubun 
Thank you for the fix!
Is it unnecessary to display a message that requires support for those who are using server_urls?
Personally it's perfect!

**Comment by k0kubun** [comment]
As it's changing the interface, existing users would see an error message when they upgrade it, and I'm going to imply the breaking change by bumping the minor version under v0.

**Comment by k0kubun** [comment]
merged https://github.com/k0kubun/rspec-openapi/pull/61
