### ISSUE TITLE
"format" in path parameter

### ISSUE THREAD

**Issue by natsuokawai** [k0kubun/rspec-openapi#8]
Hello. Thank you for such a useful gem!

I have a problem.

When I make a request in json format, the path parameter should contain a key named `format`, so the generated OpenAPI schema has a key named `format` as a path parameter.
So the generated OpenAPI schema has a `format` field in the path parameters list.
Since I don't use this field as a variable in the actual path, the error occurs because there is no `format` in the URL when loaded by swagger-editor.

> Semantic error at paths./api/v1/xxxxx.get.parameters.0.name
> Path parameter "format" must have the corresponding {format} segment in the "/api/v1/xxxxx" path

Is there a problem with skipping the `format` in [lib/rspec/openapi/schema_builder.rb:39](https://github.com/k0kubun/rspec-openapi/blob/3f94758c50a8a6116e71ce2579e670e3492f1553/lib/rspec/openapi/schema_builder.rb#L39) in the same way as the `action` and `controller`?

**Comment by k0kubun** [comment]
It's hard to understand the problem without code. Could you provide a request spec and/or a repository which reproduces the issue, and expected OpenAPI schema generated by that?

**Comment by natsuokawai** [comment]
step to reproduce:
```sh
$ git clone git@github.com:natsuokawai/rspec-openapi-sample.git
$ cd rspec-openapi-sample
$ bundle install
$ rm doc/openapi.yaml
$ OPENAPI=1 bundle exec rspec spec/requests/api/posts_spec.rb
```
In this repository, I configure routes file like this:
```rb
```

`openapi.yaml` that produced is as follows:
```yaml
...
paths:
  "/api/posts":
    get:
      summary: 'api/posts #index'
      parameters:
      - name: format
        in: path
        required: true
        schema:
          type: string
        example: json
      - name: title
        in: query
        schema:
          type: string
        example: f
...
```

but I expect is:
```yaml
openapi: 3.0.3
info:
  title: rspec-openapi-sample
paths:
  "/api/posts":
    get:
      summary: 'api/posts #index'
      parameters:
      - name: format
        in: path
        required: true
        schema:
          type: string
        example: json
      - name: title
        in: query
        schema:
          type: string
        example: f
      responses:
        '200':
          description: get posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
              example:
                posts:
                - title: foo
```

**Comment by k0kubun** [comment]
Thanks for providing the repository. 

> The generated file has a format in parameters field, but I expect is:

```yml
...
      parameters:
      - name: format
        in: path
        required: true
        schema:
          type: string
        example: json
...
```

What you expect also includes `format`, but I guess you intended to remove it?

**Comment by k0kubun** [comment]
I pushed a new version v0.3.2 which I believe fixes the issue. Could you try that?

**Comment by natsuokawai** [comment]
I have tried the new version and confirmed that this problem is no longer occurring. Thank you so much!
